[package]
name = "bsprenderer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
gooseboy = { path = "../../gooseboy" }
qbsp = "0.13.0"

[build-dependencies]
gooseboy_buildscript = { path = "../../buildscript" }
