[package]
name = "goosegpu"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
gooseboy = { path = "../../gooseboy" }

[build-dependencies]
gooseboy_buildscript = { path = "../../buildscript" }
