[package]
name = "doom"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
gooseboy = { path = "../gooseboy" }
lazy_static = "1.5.0"

[build-dependencies]
cc = "1.2.44"
