[alias]
bdebug = "run -p xtask"
brelease = "run -p xtask -- example --release"
btests = "run -p xtask -- tests"
bdoom = "run -p xtask -- doom"
bci = "run -p xtask -- doom --release --no-copy"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
