[alias]
bdebug = "run -p xtask -- example"
brelease = "run -p xtask -- example --release"
btests = "run -p xtask -- tests"
bci = "run -p xtask -- example2 --release --no-copy"
bdebug2 = "run -p xtask -- example2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
