[alias]
bgeneric = "run -p xtask -- generic"
btests = "run -p xtask -- tests"
bapple = "run -p xtask -- badapple"
bci = "run -p xtask -- all --release --no-copy"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
