[alias]
btests = "run -p xtask -- tests"
baxolotl = "run -p xtask -- axolotl"
bgeneric = "run -p xtask -- generic"
bapple = "run -p xtask -- badapple"
bch8 = "run -p xtask -- chip8"
bdoom = "run -p xtask -- doom"
bphysics = "run -p xtask -- physics"
bgpu = "run -p xtask -- goosegpu"
bbsp = "run -p xtask -- bsprenderer"
briscv = "run -p xtask -- riscv"
bci = "run -p xtask -- all --release --no-copy"
ball = "run -p xtask -- all"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
