[alias]
btests = "run -p xtask -- tests"
bgeneric = "run -p xtask -- generic"
bapple = "run -p xtask -- badapple"
bch8 = "run -p xtask -- chip8"
bdoom = "run -p xtask -- doom"
bci = "run -p xtask -- all --release --no-copy"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
