[package]
name = "gooseboy"
version = "0.2.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
gooseboy_macros = { path = "../macros" }
vek = { version = "0.17.2", default-features = false, features = ["std"] }
